# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/ui/main_w.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 729)
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.src = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.src.setGeometry(QtCore.QRect(10, 10, 371, 671))
        font = QtGui.QFont()
        font.setFamily("Source Code Pro Medium")
        font.setPointSize(12)
        self.src.setFont(font)
        self.src.setObjectName("src")
        self.TMO = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TMO.setGeometry(QtCore.QRect(390, 10, 341, 581))
        self.TMO.setReadOnly(True)
        self.TMO.setObjectName("TMO")
        self.TIM = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.TIM.setGeometry(QtCore.QRect(740, 10, 341, 241))
        self.TIM.setReadOnly(True)
        self.TIM.setObjectName("TIM")
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setGeometry(QtCore.QRect(630, 620, 101, 32))
        self.reset_btn.setObjectName("reset_btn")
        self.one_step_btn = QtWidgets.QPushButton(self.centralwidget)
        self.one_step_btn.setGeometry(QtCore.QRect(389, 600, 131, 32))
        self.one_step_btn.setObjectName("one_step_btn")
        self.all_btn = QtWidgets.QPushButton(self.centralwidget)
        self.all_btn.setGeometry(QtCore.QRect(530, 600, 90, 32))
        self.all_btn.setObjectName("all_btn")
        self.err = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.err.setGeometry(QtCore.QRect(740, 580, 341, 96))
        self.err.setReadOnly(True)
        self.err.setObjectName("err")
        self.vars = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.vars.setGeometry(QtCore.QRect(1090, 10, 341, 241))
        self.vars.setReadOnly(True)
        self.vars.setObjectName("vars")
        self.one_step_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.one_step_btn_2.setGeometry(QtCore.QRect(389, 640, 131, 32))
        self.one_step_btn_2.setObjectName("one_step_btn_2")
        self.all_btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.all_btn_2.setGeometry(QtCore.QRect(530, 640, 90, 32))
        self.all_btn_2.setObjectName("all_btn_2")
        self.sp_res = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.sp_res.setGeometry(QtCore.QRect(1090, 260, 341, 421))
        self.sp_res.setReadOnly(True)
        self.sp_res.setObjectName("sp_res")
        self.fp_res = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.fp_res.setGeometry(QtCore.QRect(740, 260, 341, 311))
        self.fp_res.setReadOnly(True)
        self.fp_res.setObjectName("fp_res")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reset_btn.setText(_translate("MainWindow", "Reset"))
        self.one_step_btn.setText(_translate("MainWindow", "One step (1)"))
        self.all_btn.setText(_translate("MainWindow", "All (1)"))
        self.one_step_btn_2.setText(_translate("MainWindow", "One step (2)"))
        self.all_btn_2.setText(_translate("MainWindow", "All (2)"))
